### PR TITLE
Add files via upload for account page

### PR DESCRIPTION
**Pull request by drewlearnsabout**

### CODE REVIEW

**Review by hmarcks — CHANGES_REQUESTED** [review]
Howdy @drewlearnsabout , we don't want to include the `<head>` and `<nav>` in this template because they get included when it's compiled. Check out the edit-user.html file for an example. Thanks!

**Review by drewlearnsabout — COMMENTED** [review]
Removed the head and nav. Sorry @hmarcks !!

**Comment by hmarcks** [comment]
Hi @drewlearnsabout, take a look at the page when you run it locally. You'll see that there's an extra nav and the layout and styles don't match the rest of the views (mainly the edit-user.html view). Let me know if you'd like any help getting your local environment running.

Also, your repo is out of date from this one, so you'll want to pull the changes into your repo so you have the most updated code.

**Comment by drewlearnsabout** [comment]
Hey @hmarcks , I apologize, but I am confused on how to pull your repo into mine to keep it updated, I need your help.

**Comment by hmarcks** [comment]
No problem @drewlearnsabout! Let me know on Slack if you'd like to set up some time to go over it, or we can take a look at the next meeting.

**Pull request closed without merging**
